version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
  app:
    image: lordstabbopriceapp:1.0
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgresdb
    ports:
      - 8282:8282
